services:
  energy-forecast-proxy:
    build:
      context: energyforecast
      dockerfile: Dockerfile
    image: energy-forecast-proxy:latest
    restart: unless-stopped
    networks:
       - traefik
    labels:
      - "traefik.http.services.energyproxy.loadbalancer.server.port=8000"
      - "traefik.enable=true"
      - "traefik.http.routers.energyproxy.rule=Host(`batctl-energyforecast.bitcave.cc`)"
      - "traefik.http.routers.energyproxy.entryPoints=web"
      - "traefik.http.routers.energyproxy.middlewares=https-redirect@file"
      - "traefik.http.routers.energyproxy-ssl.rule=Host(`batctl-energyforecast.bitcave.cc`)"
      - "traefik.http.routers.energyproxy-ssl.entryPoints=websecure"
      - "traefik.http.routers.energyproxy-ssl.tls=true"
      - "traefik.http.routers.energyproxy-ssl.tls.certresolver=lets-encrypt"

networks:
  iobrokernet:
    external: true
  traefik:
    external:
       name: traefik_proxy

